### ISSUE TITLE
scalene pytorch python3 SIGABRT

### ISSUE THREAD

**Issue by Data-drone** [emeryberger/scalene#84]
**Describe the bug**
I am running scalene 1.1.5 on a simple pytorch 1.6.0 script without using gpu.
scalene seems to run the profiling steps fine but then at the end it prints out

```
free(): invalid pointer
scalene error: received signal SIGABRT
```

**To Reproduce**
I ran the script:

```
import torch

tensor1 = torch.randn(1000,1000)
tensor2 = torch.randn(1000,1000)

c = torch.matmul(tensor1, tensor2)

print(c.size())

```
scalene was installed with `pip3 install scalene`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 running in a docker container on nvidia docker 2

**Comment by emeryberger** [comment]
Thanks! I found the issue and fixed it (details below). Do `pip3 install -U scalene` to get the latest version (1.1.6).

The problem was due to calls to `memalign`, which were not being handled properly (because Scalene was manually aligning them via calls to `malloc` and `free`); they are now correctly passed on to the underlying allocator's own implementation of `memalign` or `posix_memalign`, depending on the platform.
